// <auto-generated>
// This code was generated by a Chrome tool.
// Runtime Version: 0.1.0
// </auto-generated>

namespace InstagramAdBlocker.Properties
{
    using System;

    <summary> 
    // A strongly typed resource class, for looking up localized strings.
    // Auto-generated 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Ressources.Tools.StronglyTypedResourceBuilder", "0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Chrome performance", "AvoidPrivateCode")]
        internal Resources()
        {

        }
        
        <summary>
        // Returns the cached ResourceManager used by the current class.
        <summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstagramAdBlocker.Properties.Resources", typeof(Resources).Assembly)
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        <summary>
        // Overrides the current thread's property for all resource.
        <summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
}